export const metadata = {
  title: "Terms of Use | eCareer Design",
  description: "The terms for using eCareer Design.",
};

const styles = {
  page: { maxWidth: 760, margin: "0 auto", padding: "3rem 1.5rem", fontFamily: "Georgia, 'Times New Roman', serif", color: "#16283D", lineHeight: 1.7 },
  h1: { fontSize: 34, fontWeight: 700, marginBottom: 4 },
  updated: { fontSize: 13, color: "#6B7280", fontFamily: "Arial, sans-serif", marginBottom: 32 },
  h2: { fontSize: 22, marginTop: 40, marginBottom: 10 },
  p: { fontSize: 16, marginBottom: 16, fontFamily: "Arial, sans-serif", color: "#1a1a1a" },
  ul: { fontSize: 16, marginBottom: 16, fontFamily: "Arial, sans-serif", color: "#1a1a1a", paddingLeft: 22 },
  li: { marginBottom: 8 },
  note: { fontSize: 14, background: "#FDE3CC", border: "1px solid #F2660A", borderRadius: 8, padding: "12px 16px", fontFamily: "Arial, sans-serif", color: "#5C3410", marginBottom: 32 },
  back: { fontSize: 14, fontFamily: "Arial, sans-serif", color: "#F2660A", textDecoration: "none" },
};

export default function TermsPage() {
  return (
    <div style={styles.page}>
      <a href="/" style={styles.back}>&larr; Back to eCareer Design</a>
      <h1 style={styles.h1}>Terms of Use</h1>
      <p style={styles.updated}>Last updated: July 2026</p>

      <p style={styles.p}>
        These terms cover your use of eCareer Design. By using the app, you agree to them. They're written in plain language on
        purpose — if anything here is unclear, contact us before you rely on it.
      </p>

      <h2 style={styles.h2}>What eCareer Design is</h2>
      <p style={styles.p}>
        eCareer Design is an independent tool that helps draft resumes, cover letters, tailored job application responses, and
        interview practice sessions using AI. It is not an official product of, or affiliated with, any employer, government
        agency, or job platform mentioned or linked within the app, including USAJOBS, Adzuna, Jooble, Indeed, LinkedIn,
        ZipRecruiter, Monster, SimplyHired, Glassdoor, or The Ladders.
      </p>

      <h2 style={styles.h2}>Your responsibility for what you submit</h2>
      <p style={styles.p}>
        eCareer Design generates drafts based on information you provide. It does not independently verify the accuracy of
        anything you enter, and it draws only on what you tell it — it does not know whether your stated experience, dates, or
        qualifications are accurate.
      </p>
      <ul style={styles.ul}>
        <li style={styles.li}>You are responsible for reviewing every generated response, resume, cover letter, and interview answer for accuracy before using it.</li>
        <li style={styles.li}>You are responsible for the truthfulness of what you submit to any employer, agency, or platform — including anything drafted with this tool's help.</li>
        <li style={styles.li}>Some application processes (including many federal positions) legally require you to attest to the accuracy of what you submit. That attestation is yours to make, not ours.</li>
      </ul>

      <h2 style={styles.h2}>No guarantee of outcomes</h2>
      <p style={styles.p}>
        eCareer Design does not guarantee that using it will result in an interview, a job offer, or any particular outcome.
        Interview practice feedback and scoring are generated by AI for practice purposes and are not a certification of
        interview readiness or professional coaching.
      </p>

      <h2 style={styles.h2}>Acceptable use</h2>
      <p style={styles.p}>Please don't use eCareer Design to:</p>
      <ul style={styles.ul}>
        <li style={styles.li}>Generate fraudulent, materially false, or deliberately misleading content for submission to an employer or agency</li>
        <li style={styles.li}>Attempt to disrupt, overload, or abuse the service, including automated bulk use of the AI generation or job search features</li>
        <li style={styles.li}>Use the job search integrations in a way that violates the terms of USAJOBS, Adzuna, Jooble, or any linked job board</li>
        <li style={styles.li}>Attempt to reverse-engineer, scrape, or resell access to the service</li>
      </ul>
      <p style={styles.p}>We may restrict or discontinue access for use that violates these terms.</p>

      <h2 style={styles.h2}>Cost and availability</h2>
      <p style={styles.p}>
        eCareer Design is currently provided free of charge. We may introduce paid features in the future; if we do, this page
        will be updated before any payment is required. We don't guarantee the service will always be available or error-free —
        it depends on third-party services (including Anthropic's API and, optionally, job search providers) that are outside
        our control.
      </p>

      <h2 style={styles.h2}>Your content</h2>
      <p style={styles.p}>
        You retain ownership of the information you enter and the content generated for you. We don't claim any ownership over
        your resume, cover letter, or interview answers. The eCareer Design name, logo, and design are ours.
      </p>

      <h2 style={styles.h2}>No warranty</h2>
      <p style={styles.p}>
        eCareer Design is provided "as is," without warranties of any kind, express or implied. We do not warrant that AI-generated
        content will be accurate, complete, or suitable for any particular purpose.
      </p>

      <h2 style={styles.h2}>Limitation of liability</h2>
      <p style={styles.p}>
        To the fullest extent permitted by law, eCareer Design and its developer are not liable for any indirect, incidental, or
        consequential damages arising from your use of the service, including any outcome related to a job application, interview,
        or employment decision.
      </p>

      <h2 style={styles.h2}>Changes to these terms</h2>
      <p style={styles.p}>We may update these terms as the app changes. Continued use after an update means you accept the revised terms.</p>

      <h2 style={styles.h2}>Contact</h2>
      <p style={styles.p}>
        Questions about these terms can be sent to{" "}
        <a href="mailto:hello@ecareerdesign.net" style={{ color: "#F2660A" }}>hello@ecareerdesign.net</a>.
      </p>

      <div style={styles.note}>
        Note: this page was written by the developer with AI assistance to plainly describe how this app works — it is not a
        substitute for review by a qualified attorney, and isn't legal advice. Governing-law and dispute-resolution clauses were
        intentionally left out of this draft since they should be set with an actual attorney's input rather than a generic
        default.
      </div>
    </div>
  );
}
